[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ome_zarr_pyramid"
version = "0.0.5"
description = "Read, write and downscale OME-Zarr (NGFF) pyramids with a lazy, memory-bound Pyramid object"
readme = "README.md"
requires-python = ">=3.8"
authors = [ { name = "Bugra Özdemir", email = "bugraa.ozdemir@gmail.com" } ]
keywords = ["ome", "zarr", "pyramid"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "zarr",
    "dask",
    "tensorstore",
]

[project.optional-dependencies]
s3 = ["s3fs"]

[project.urls]
Homepage = "https://github.com/Euro-BioImaging/ome_zarr_pyramid"

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*"]
